import { HighlightedNextHeader, Header } from "@components/utilities/Headers";
import { SouthEast, NorthEast } from "@mui/icons-material";
import { Box, Typography } from "@mui/material";
import type { NextPage } from "next";
import Link from "next/link";

const Ido: NextPage = () => {
  return (
    <>
    <Box sx={{ width: "100%" }}>
      <Box sx={{ display: "flex", width: "100%" }}>
        <Box sx={{ width: "50%" }}>
          <SouthEast color="primary" sx={{ fontSize: "3rem" }} />
          <HighlightedNextHeader
            before={"All about the "}
            highlighted={"IDO"}
            after={""}
            button={"Join the IDO"}
          />
        </Box>
      </Box>
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="All about Spreadly"
          subtitle="Spreadly is an organization whose purpose is to create a functional, secure, and easily accessible prediction markets. It will make it easy for anyone to place and take bets in a peer-to-peer fashion. Through the DAO, revenue generated by markets is redistributed to users who interact with the platform the most."
        />
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="Why Spreadly?"
          subtitle="Spreadly is radically different from other prediction markets. The mission is to serve the users of the protocol. The DAO does this by redistributing revenue to its members."
        />
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="Tokenomics"
          subtitle="Spreadly is an organization whose purpose is to create a functional, secure, and easily accessible prediction markets. It will make it easy for anyone to place and take bets in a peer-to-peer fashion. Through the DAO, revenue generated by markets is redistributed to users who interact with the platform the most."
          button="MORE ON TOKENOMICS"
        />
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="Why is the token valuable?"
          subtitle='This website is operated by the Design Files. Throughout the site, the terms "we", "us", and "our" refer to the Design Files. The Design Files offers this website, including all information, tools, and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies, and notices stated here.'
        />
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="When rewards?"
          subtitle='Acme automates your subscription revenue and customer reporting. Just connect your data and Acme will calculate and visualize your most important metrics.'
        />
    </Box>
    <Box sx={{ width: "70%", display: "flex", alignItems: "center" }}>
        <Header
          title="How the IDO Works?"
          subtitle='This website is operated by the Design Files. Throughout the site, the terms "we", "us", and "our" refer to the Design Files. The Design Files offers this website, including all information, tools, and service available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies, and notices stated here.'
        />
    </Box>
    </>
  );
};

export default Ido;
